banner:
  enable: true
  title: 踏着梦走过时光
  border: true
  cloud:
    enable: true
    color: white
  go_down:
    enable: true
    icon: ri:arrow-down-s-line
notice:
  enable: true
  content: 欢迎光临我的世界
avatar:
  enable: true
  url: /images/abvatar.jpg
  rounded: true
  opacity: 1
  mickey_mouse: false
  status:
    enable: true
    emoji: ☺️
    message: 四季花开
social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange
  - name: GitHub
    link: https://github.com/QIngMengK
    icon: ri:github-line
    color: '#181717'
  - name: E-Mail
    link: 85256952@qq.com
    icon: ri:mail-line
    color: '#8E71C1'
  # - name: 微博
  #   link: #
  #   icon: ri:weibo-line
  #   color: '#E6162D'
  # - name: 豆瓣
  #   link: #
  #   icon: ri:douban-line
  #   color: '#007722'
  - name: 网易云音乐
    link: https://music.163.com/#/user/home?id=5113221006
    icon: ri:netease-cloud-music-line
    color: '#C10D0C'
  - name: 哔哩哔哩
    link: https://space.bilibili.com/1784222941?spm_id_from=333.1007.0.0
    icon: ri:bilibili-line
    color: '#FF8EB3'
  # - name: 微信公众号
  #   link: #
  #   icon: ri:wechat-2-line
  #   color: '#1AAD19'
# _config.yun.yml

bg_image:
  enable: true
  url: /images/background.jpg
  # dark:
  blur: 10px # 设置背景模糊程度
  opacity: 0.6
